# Generated by Django 2.2 on 2020-05-01 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('jobType', models.CharField(max_length=30, verbose_name='type')),
                ('salary', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='salary')),
                ('tags', models.CharField(blank=True, max_length=100, verbose_name='tags')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='pub_date')),
                ('image', models.ImageField(default='defaultJobImg.jpg', upload_to='opportunities', verbose_name='opImage')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('link', models.CharField(max_length=2000, verbose_name='link')),
            ],
        ),
    ]
