# Generated by Django 2.2 on 2020-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='salary',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='company',
            field=models.CharField(blank=True, max_length=30, verbose_name='company'),
        ),
    ]
