# Generated by Django 2.2 on 2020-05-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_auto_20200501_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='description',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='pub_date'),
        ),
    ]
