# Generated by Django 2.2 on 2020-05-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_auto_20200502_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(default='Lebanon', max_length=50, verbose_name='location'),
            preserve_default=False,
        ),
    ]
