# Generated by Django 2.2 on 2020-05-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_opportunity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='link',
            field=models.CharField(max_length=2000, unique=True, verbose_name='link'),
        ),
    ]
