# Generated by Django 2.2 on 2020-05-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_auto_20200502_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(default='defaultJobImg.jpg', upload_to='opportunities', verbose_name='opImage'),
        ),
    ]
